// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package com.reu.serializationtest;

public final class BookProtos {
  private BookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BookProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string title = 1;
    boolean hasTitle();
    String getTitle();
    
    // required string author = 2;
    boolean hasAuthor();
    String getAuthor();
    
    // optional string description = 3;
    boolean hasDescription();
    String getDescription();
    
    // optional string image = 4;
    boolean hasImage();
    String getImage();
    
    // required int32 numInStock = 5;
    boolean hasNumInStock();
    int getNumInStock();
    
    // required double price = 6;
    boolean hasPrice();
    double getPrice();
    
    // required bool onSale = 7;
    boolean hasOnSale();
    boolean getOnSale();
    
    // required .serializertest.BookProto.BookType type = 8;
    boolean hasType();
    com.reu.serializationtest.BookProtos.BookProto.BookType getType();
  }
  public static final class BookProto extends
      com.google.protobuf.GeneratedMessage
      implements BookProtoOrBuilder {
    // Use BookProto.newBuilder() to construct.
    private BookProto(Builder builder) {
      super(builder);
    }
    private BookProto(boolean noInit) {}
    
    private static final BookProto defaultInstance;
    public static BookProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public BookProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reu.serializationtest.BookProtos.internal_static_serializertest_BookProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reu.serializationtest.BookProtos.internal_static_serializertest_BookProto_fieldAccessorTable;
    }
    
    public enum BookType
        implements com.google.protobuf.ProtocolMessageEnum {
      PAPERBACK(0, 0),
      HARDCOVER(1, 1),
      DIGITAL(2, 2),
      ;
      
      public static final int PAPERBACK_VALUE = 0;
      public static final int HARDCOVER_VALUE = 1;
      public static final int DIGITAL_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static BookType valueOf(int value) {
        switch (value) {
          case 0: return PAPERBACK;
          case 1: return HARDCOVER;
          case 2: return DIGITAL;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<BookType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<BookType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BookType>() {
              public BookType findValueByNumber(int number) {
                return BookType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.reu.serializationtest.BookProtos.BookProto.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final BookType[] VALUES = {
        PAPERBACK, HARDCOVER, DIGITAL, 
      };
      
      public static BookType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private BookType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:serializertest.BookProto.BookType)
    }
    
    private int bitField0_;
    // required string title = 1;
    public static final int TITLE_FIELD_NUMBER = 1;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string author = 2;
    public static final int AUTHOR_FIELD_NUMBER = 2;
    private java.lang.Object author_;
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getAuthor() {
      java.lang.Object ref = author_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          author_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string image = 4;
    public static final int IMAGE_FIELD_NUMBER = 4;
    private java.lang.Object image_;
    public boolean hasImage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getImage() {
      java.lang.Object ref = image_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          image_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getImageBytes() {
      java.lang.Object ref = image_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        image_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 numInStock = 5;
    public static final int NUMINSTOCK_FIELD_NUMBER = 5;
    private int numInStock_;
    public boolean hasNumInStock() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getNumInStock() {
      return numInStock_;
    }
    
    // required double price = 6;
    public static final int PRICE_FIELD_NUMBER = 6;
    private double price_;
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public double getPrice() {
      return price_;
    }
    
    // required bool onSale = 7;
    public static final int ONSALE_FIELD_NUMBER = 7;
    private boolean onSale_;
    public boolean hasOnSale() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public boolean getOnSale() {
      return onSale_;
    }
    
    // required .serializertest.BookProto.BookType type = 8;
    public static final int TYPE_FIELD_NUMBER = 8;
    private com.reu.serializationtest.BookProtos.BookProto.BookType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.reu.serializationtest.BookProtos.BookProto.BookType getType() {
      return type_;
    }
    
    private void initFields() {
      title_ = "";
      author_ = "";
      description_ = "";
      image_ = "";
      numInStock_ = 0;
      price_ = 0D;
      onSale_ = false;
      type_ = com.reu.serializationtest.BookProtos.BookProto.BookType.PAPERBACK;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAuthor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNumInStock()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOnSale()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTitleBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAuthorBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getImageBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, numInStock_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, price_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, onSale_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(8, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTitleBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAuthorBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getImageBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, numInStock_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, price_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, onSale_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.reu.serializationtest.BookProtos.BookProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.reu.serializationtest.BookProtos.BookProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.reu.serializationtest.BookProtos.BookProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.reu.serializationtest.BookProtos.BookProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.reu.serializationtest.BookProtos.BookProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.reu.serializationtest.BookProtos.BookProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.reu.serializationtest.BookProtos.BookProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.reu.serializationtest.BookProtos.BookProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.reu.serializationtest.BookProtos.BookProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.reu.serializationtest.BookProtos.BookProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.reu.serializationtest.BookProtos.BookProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.reu.serializationtest.BookProtos.BookProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reu.serializationtest.BookProtos.internal_static_serializertest_BookProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reu.serializationtest.BookProtos.internal_static_serializertest_BookProto_fieldAccessorTable;
      }
      
      // Construct using com.reu.serializationtest.BookProtos.BookProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        author_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        image_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        numInStock_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        price_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        onSale_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        type_ = com.reu.serializationtest.BookProtos.BookProto.BookType.PAPERBACK;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reu.serializationtest.BookProtos.BookProto.getDescriptor();
      }
      
      public com.reu.serializationtest.BookProtos.BookProto getDefaultInstanceForType() {
        return com.reu.serializationtest.BookProtos.BookProto.getDefaultInstance();
      }
      
      public com.reu.serializationtest.BookProtos.BookProto build() {
        com.reu.serializationtest.BookProtos.BookProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.reu.serializationtest.BookProtos.BookProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.reu.serializationtest.BookProtos.BookProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.reu.serializationtest.BookProtos.BookProto buildPartial() {
        com.reu.serializationtest.BookProtos.BookProto result = new com.reu.serializationtest.BookProtos.BookProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.author_ = author_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.image_ = image_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.numInStock_ = numInStock_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.onSale_ = onSale_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reu.serializationtest.BookProtos.BookProto) {
          return mergeFrom((com.reu.serializationtest.BookProtos.BookProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.reu.serializationtest.BookProtos.BookProto other) {
        if (other == com.reu.serializationtest.BookProtos.BookProto.getDefaultInstance()) return this;
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasAuthor()) {
          setAuthor(other.getAuthor());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasImage()) {
          setImage(other.getImage());
        }
        if (other.hasNumInStock()) {
          setNumInStock(other.getNumInStock());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasOnSale()) {
          setOnSale(other.getOnSale());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasAuthor()) {
          
          return false;
        }
        if (!hasNumInStock()) {
          
          return false;
        }
        if (!hasPrice()) {
          
          return false;
        }
        if (!hasOnSale()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              title_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              author_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              image_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              numInStock_ = input.readInt32();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              price_ = input.readDouble();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              onSale_ = input.readBool();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              com.reu.serializationtest.BookProtos.BookProto.BookType value = com.reu.serializationtest.BookProtos.BookProto.BookType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                type_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string title = 1;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        title_ = value;
        onChanged();
      }
      
      // required string author = 2;
      private java.lang.Object author_ = "";
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getAuthor() {
        java.lang.Object ref = author_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          author_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAuthor(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        author_ = value;
        onChanged();
        return this;
      }
      public Builder clearAuthor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        author_ = getDefaultInstance().getAuthor();
        onChanged();
        return this;
      }
      void setAuthor(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        author_ = value;
        onChanged();
      }
      
      // optional string description = 3;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
      }
      
      // optional string image = 4;
      private java.lang.Object image_ = "";
      public boolean hasImage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getImage() {
        java.lang.Object ref = image_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          image_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setImage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        image_ = value;
        onChanged();
        return this;
      }
      public Builder clearImage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        image_ = getDefaultInstance().getImage();
        onChanged();
        return this;
      }
      void setImage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        image_ = value;
        onChanged();
      }
      
      // required int32 numInStock = 5;
      private int numInStock_ ;
      public boolean hasNumInStock() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getNumInStock() {
        return numInStock_;
      }
      public Builder setNumInStock(int value) {
        bitField0_ |= 0x00000010;
        numInStock_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumInStock() {
        bitField0_ = (bitField0_ & ~0x00000010);
        numInStock_ = 0;
        onChanged();
        return this;
      }
      
      // required double price = 6;
      private double price_ ;
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public double getPrice() {
        return price_;
      }
      public Builder setPrice(double value) {
        bitField0_ |= 0x00000020;
        price_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000020);
        price_ = 0D;
        onChanged();
        return this;
      }
      
      // required bool onSale = 7;
      private boolean onSale_ ;
      public boolean hasOnSale() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public boolean getOnSale() {
        return onSale_;
      }
      public Builder setOnSale(boolean value) {
        bitField0_ |= 0x00000040;
        onSale_ = value;
        onChanged();
        return this;
      }
      public Builder clearOnSale() {
        bitField0_ = (bitField0_ & ~0x00000040);
        onSale_ = false;
        onChanged();
        return this;
      }
      
      // required .serializertest.BookProto.BookType type = 8;
      private com.reu.serializationtest.BookProtos.BookProto.BookType type_ = com.reu.serializationtest.BookProtos.BookProto.BookType.PAPERBACK;
      public boolean hasType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.reu.serializationtest.BookProtos.BookProto.BookType getType() {
        return type_;
      }
      public Builder setType(com.reu.serializationtest.BookProtos.BookProto.BookType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        type_ = com.reu.serializationtest.BookProtos.BookProto.BookType.PAPERBACK;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:serializertest.BookProto)
    }
    
    static {
      defaultInstance = new BookProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:serializertest.BookProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_serializertest_BookProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serializertest_BookProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbook.proto\022\016serializertest\"\352\001\n\tBookPro" +
      "to\022\r\n\005title\030\001 \002(\t\022\016\n\006author\030\002 \002(\t\022\023\n\013des" +
      "cription\030\003 \001(\t\022\r\n\005image\030\004 \001(\t\022\022\n\nnumInSt" +
      "ock\030\005 \002(\005\022\r\n\005price\030\006 \002(\001\022\016\n\006onSale\030\007 \002(\010" +
      "\0220\n\004type\030\010 \002(\0162\".serializertest.BookProt" +
      "o.BookType\"5\n\010BookType\022\r\n\tPAPERBACK\020\000\022\r\n" +
      "\tHARDCOVER\020\001\022\013\n\007DIGITAL\020\002B\'\n\031com.reu.ser" +
      "ializationtestB\nBookProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_serializertest_BookProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_serializertest_BookProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_serializertest_BookProto_descriptor,
              new java.lang.String[] { "Title", "Author", "Description", "Image", "NumInStock", "Price", "OnSale", "Type", },
              com.reu.serializationtest.BookProtos.BookProto.class,
              com.reu.serializationtest.BookProtos.BookProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
