/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.reu.serializationtest;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum BookType implements org.apache.thrift.TEnum {
  PAPERBACK(0),
  HARDCOVER(1),
  DIGITAL(2);

  private final int value;

  private BookType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static BookType findByValue(int value) { 
    switch (value) {
      case 0:
        return PAPERBACK;
      case 1:
        return HARDCOVER;
      case 2:
        return DIGITAL;
      default:
        return null;
    }
  }
}
